version: '3'
services:
  influxdb:
    image: influxdb:2.0.7
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/.influxdbv2
    ports:
      - "8086:8086"
# Use the influx cli to set up an influxdb instance
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.0.7
# Use these same configurations parameters in your telegraf configuration
    entrypoint: influx setup --bucket zmq -t cleandesign -o cleandesign --username=influxuser --password=password123 --host=http://influxdb:8086 -f
    # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service
    restart: on-failure:10
    depends_on:
      - influxdb
volumes:
  influxdbv2: